name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build-Publish :

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Composer update
      run: composer update

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test

    - name: Configure SSH
      run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName ${{ secrets.DEPLOY_SSH_HOST }}
            User ${{ secrets.DEPLOY_SSH_USER }}
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END

    - name: Deploy Dev
      run: bash ./setup/deploy.sh dev

    - name: Test publish
      run:  test `curl -I http://dev.zami.syllab.com 2>/dev/null | head -n 1 | cut -d ' ' -f2` -lt 300

    - name: Deploy Test
      run: bash ./setup/deploy.sh test
    
