name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build :
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Composer update
      run: composer update

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Lint yaml
      run: php ./bin/console lint:yaml config --parse-tags

    #- name: Lint Twig templates
    #  run: php ./bin/console lint:twig templates --env=prod

    #- name: Lint XLIFF translations
    #  run: php ./bin/console lint:xliff translations

    - name: Lint Parameters and Services
      run: php ./bin/console lint:container --no-debug

    #- name: Lint Doctrine entities
    #  run: php ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

    - name: Lint Composer config
      run: composer validate --strict

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: php ./bin/phpunit
    
    - name: Archive artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: zami-app
        path: |
          ./
          !vendor
          !var
          !.*      
          
  Publish-Dev :
    runs-on: ubuntu-20.04
    needs: Build
    steps:
    - uses: actions/download-artifact@v2.0.10
      with:
        name: zami-app

    - name: Configure SSH
      run: bash ./setup/sshconf.sh  
      env:
        SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
        SSH_USER: ${{ secrets.DEPLOY_SSH_USER }}
        SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Deploy Dev
      run: bash ./setup/deploy.sh dev

    - name: Test publish
      run:  test `curl -I http://dev.zami.syllab.com 2>/dev/null | head -n 1 | cut -d ' ' -f2` -lt 300

  Publish-Test :
    runs-on: ubuntu-20.04
    needs: Publish-Dev
    steps:
    - uses: actions/download-artifact@v2.0.10
      with:
        name: zami-app

    - name: Configure SSH
      run: bash ./setup/sshconf.sh  
      env:
        SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
        SSH_USER: ${{ secrets.DEPLOY_SSH_USER }}
        SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Deploy Test
      run: bash ./setup/deploy.sh test
    

